[2024-01-16T09:31:40.132+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_slack.send_slack_totalPost manual__2024-01-16T09:31:28.861826+00:00 [queued]>
[2024-01-16T09:31:40.145+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_slack.send_slack_totalPost manual__2024-01-16T09:31:28.861826+00:00 [queued]>
[2024-01-16T09:31:40.145+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-16T09:31:40.145+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-16T09:31:40.145+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-16T09:31:40.166+0000] {taskinstance.py:1300} INFO - Executing <Task(SlackWebhookOperator): send_slack_totalPost> on 2024-01-16 09:31:28.861826+00:00
[2024-01-16T09:31:40.172+0000] {standard_task_runner.py:55} INFO - Started process 72887 to run task
[2024-01-16T09:31:40.174+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_slack', 'send_slack_totalPost', 'manual__2024-01-16T09:31:28.861826+00:00', '--job-id', '761', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_slack.py', '--cfg-path', '/tmp/tmpcpfc0gdb']
[2024-01-16T09:31:40.175+0000] {standard_task_runner.py:83} INFO - Job 761: Subtask send_slack_totalPost
[2024-01-16T09:31:40.272+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_slack.send_slack_totalPost manual__2024-01-16T09:31:28.861826+00:00 [running]> on host 565f6bcc10b6
[2024-01-16T09:31:40.393+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_slack
AIRFLOW_CTX_TASK_ID=send_slack_totalPost
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T09:31:28.861826+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T09:31:28.861826+00:00
[2024-01-16T09:31:40.394+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/operators/slack_webhook.py:173: UserWarning: Found unexpected keyword-argument(s) 'link_names' in `send` method. This argument(s) have no effect.
  link_names=self.link_names,

[2024-01-16T09:31:40.405+0000] {base.py:73} INFO - Using connection ID 'slack_conn' for task execution.
[2024-01-16T09:31:40.406+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/slack/hooks/slack_webhook.py:226: DeprecationWarning: Found Slack Webhook Token URL in Connection 'slack_conn' `host` and `password` field is empty. This behaviour deprecated and could expose you token in the UI and will be removed in a future releases.
  return WebhookClient(**self._get_conn_params())

[2024-01-16T09:31:40.946+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 173, in execute
    link_names=self.link_names,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 425, in send
    return self.send_dict(body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 50, in wrapper
    f"Response body: {resp.body!r}, Status Code: {resp.status_code}. "
airflow.exceptions.AirflowException: Response body: '{"ok":false,"error":"workflow_not_published"}', Status Code: 400. See: https://api.slack.com/messaging/webhooks#handling_errors
[2024-01-16T09:31:40.950+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=jobinfo_slack, task_id=send_slack_totalPost, execution_date=20240116T093128, start_date=20240116T093140, end_date=20240116T093140
[2024-01-16T09:31:40.972+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 761 for task send_slack_totalPost (Response body: '{"ok":false,"error":"workflow_not_published"}', Status Code: 400. See: https://api.slack.com/messaging/webhooks#handling_errors; 72887)
[2024-01-16T09:31:40.994+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-16T09:31:41.024+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
