[2024-01-14T15:23:01.143+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.s3_to_rds manual__2024-01-14T15:16:17.913815+00:00 [queued]>
[2024-01-14T15:23:01.150+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.s3_to_rds manual__2024-01-14T15:16:17.913815+00:00 [queued]>
[2024-01-14T15:23:01.150+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-14T15:23:01.150+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-14T15:23:01.151+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-14T15:23:01.167+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): s3_to_rds> on 2024-01-14 15:16:17.913815+00:00
[2024-01-14T15:23:01.175+0000] {standard_task_runner.py:55} INFO - Started process 5862 to run task
[2024-01-14T15:23:01.179+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 's3_to_rds', 'manual__2024-01-14T15:16:17.913815+00:00', '--job-id', '524', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmp2f3a41kj']
[2024-01-14T15:23:01.180+0000] {standard_task_runner.py:83} INFO - Job 524: Subtask s3_to_rds
[2024-01-14T15:23:01.238+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.s3_to_rds manual__2024-01-14T15:16:17.913815+00:00 [running]> on host 565f6bcc10b6
[2024-01-14T15:23:01.323+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T15:16:17.913815+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-14T15:16:17.913815+00:00
[2024-01-14T15:23:01.336+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2024-01-14T15:23:01.596+0000] {base.py:73} INFO - Using connection ID 'rds_conn' for task execution.
[2024-01-14T15:23:01.776+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 691, in s3_to_rds
    conn.select_db('jobinfo_jobplanet')
MySQLdb.OperationalError: (1049, "Unknown database 'jobinfo_jobplanet'")
[2024-01-14T15:23:01.805+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=s3_to_rds, execution_date=20240114T151617, start_date=20240114T152301, end_date=20240114T152301
[2024-01-14T15:23:01.882+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 524 for task s3_to_rds ((1049, "Unknown database 'jobinfo_jobplanet'"); 5862)
[2024-01-14T15:23:01.925+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-14T15:23:01.965+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
