[2024-01-13T10:51:16.820+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T10:51:06.430387+00:00 [queued]>
[2024-01-13T10:51:16.840+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T10:51:06.430387+00:00 [queued]>
[2024-01-13T10:51:16.841+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T10:51:16.841+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-13T10:51:16.841+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-13T10:51:16.875+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_infomation_s3> on 2024-01-13 10:51:06.430387+00:00
[2024-01-13T10:51:16.881+0000] {standard_task_runner.py:55} INFO - Started process 2718 to run task
[2024-01-13T10:51:16.885+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 'create_infomation_s3', 'manual__2024-01-13T10:51:06.430387+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmps_78iyj1']
[2024-01-13T10:51:16.885+0000] {standard_task_runner.py:83} INFO - Job 339: Subtask create_infomation_s3
[2024-01-13T10:51:17.156+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-13T10:51:06.430387+00:00 [running]> on host 9d92fdf7265b
[2024-01-13T10:51:17.227+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=create_infomation_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T10:51:06.430387+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-13T10:51:06.430387+00:00
[2024-01-13T10:51:17.228+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 81, in create_infomation_s3
    driver = jobplanet_login()
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 49, in jobplanet_login
    driver = webdriver.Chrome(executable_path='/usr/src/chrome')
TypeError: __init__() got an unexpected keyword argument 'executable_path'
[2024-01-13T10:51:17.235+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=create_infomation_s3, execution_date=20240113T105106, start_date=20240113T105116, end_date=20240113T105117
[2024-01-13T10:51:17.249+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 339 for task create_infomation_s3 (__init__() got an unexpected keyword argument 'executable_path'; 2718)
[2024-01-13T10:51:17.299+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-13T10:51:17.500+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
