[2024-01-14T11:35:32.251+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-14T11:35:21.625926+00:00 [queued]>
[2024-01-14T11:35:32.273+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-14T11:35:21.625926+00:00 [queued]>
[2024-01-14T11:35:32.275+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-14T11:35:32.275+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-14T11:35:32.275+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-14T11:35:32.306+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_infomation_s3> on 2024-01-14 11:35:21.625926+00:00
[2024-01-14T11:35:32.321+0000] {standard_task_runner.py:55} INFO - Started process 21993 to run task
[2024-01-14T11:35:32.327+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'jobinfo_jobplanet', 'create_infomation_s3', 'manual__2024-01-14T11:35:21.625926+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/jobinfo_jobplanet.py', '--cfg-path', '/tmp/tmpna7ps7zb']
[2024-01-14T11:35:32.330+0000] {standard_task_runner.py:83} INFO - Job 465: Subtask create_infomation_s3
[2024-01-14T11:35:33.105+0000] {task_command.py:388} INFO - Running <TaskInstance: jobinfo_jobplanet.create_infomation_s3 manual__2024-01-14T11:35:21.625926+00:00 [running]> on host 7b77d04f99d6
[2024-01-14T11:35:33.327+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=jobinfo_jobplanet
AIRFLOW_CTX_TASK_ID=create_infomation_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T11:35:21.625926+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-14T11:35:21.625926+00:00
[2024-01-14T11:35:33.330+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobinfo_jobplanet.py", line 128, in create_infomation_s3
    logging.info(driver)
UnboundLocalError: local variable 'driver' referenced before assignment
[2024-01-14T11:35:33.345+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=jobinfo_jobplanet, task_id=create_infomation_s3, execution_date=20240114T113521, start_date=20240114T113532, end_date=20240114T113533
[2024-01-14T11:35:33.402+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 465 for task create_infomation_s3 (local variable 'driver' referenced before assignment; 21993)
[2024-01-14T11:35:33.468+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-14T11:35:33.905+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
